# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveImageForm',
            new_name='SaveFileForm',
        ),
        migrations.AlterModelTable(
            name='savefileform',
            table='SaveFileForm',
        ),
    ]
