# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170609_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='testingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datatesting', models.FileField(upload_to='datatesting')),
            ],
            options={
                'db_table': 'jsonfiletesting',
            },
        ),
    ]
