# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
