# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170609_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='featurelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featurelist', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'featureList',
            },
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='datatesting',
            field=models.FileField(upload_to=''),
        ),
    ]
