# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170617_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurelist',
            old_name='featurelist',
            new_name='FeatureList',
        ),
    ]
