# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170617_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelist',
            name='FeatureList',
            field=models.FileField(upload_to='featurelist'),
        ),
        migrations.AlterField(
            model_name='featurelist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
