# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170617_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='tag',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False),
        ),
    ]
