# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170619_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopwords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stopwords', models.FileField(upload_to='stopwords')),
            ],
            options={
                'db_table': 'stopwords',
            },
        ),
        migrations.RenameModel(
            old_name='SaveFileForm',
            new_name='ModelTraining',
        ),
        migrations.AlterModelTable(
            name='modeltraining',
            table='modeltraining',
        ),
    ]
